# Generated by Django 3.1.12 on 2025-02-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('entrante', 'Entrante'), ('principal', 'Principal'), ('postre', 'Postre')], max_length=20)),
                ('restricciones', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('ubicacion', models.CharField(help_text='Ciudad o zona', max_length=255)),
                ('tipologia', models.CharField(help_text='Ej. Mediterráneo, Vegano, etc.', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionRestaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='Identificador del comensal', max_length=255)),
                ('puntuacion', models.IntegerField(help_text='Valoración numérica (por ejemplo, 1-5)')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='la_cuchara_app.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionPlato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='Identificador del comensal', max_length=255)),
                ('puntuacion', models.IntegerField(help_text='Valoración numérica (1-5)')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='la_cuchara_app.plato')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='Identificador del comensal', max_length=255)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('platos', models.JSONField(blank=True, help_text='Listado de platos solicitados', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='la_cuchara_app.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_promocional', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('importe_diario', models.DecimalField(decimal_places=2, help_text='Importe pagado diariamente', max_digits=6)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='la_cuchara_app.plato')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='la_cuchara_app.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('menu', 'Menú Diario'), ('carta', 'Carta')], max_length=10)),
                ('fecha', models.DateField(blank=True, help_text='Fecha para la que aplica el menú', null=True)),
                ('platos', models.JSONField(blank=True, help_text='Lista de platos con detalles (nombre, precio, restricciones, etc.)', null=True)),
                ('archivo_url', models.URLField(help_text='URL del archivo almacenado en Blob Storage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='la_cuchara_app.restaurante')),
            ],
        ),
    ]
